const defaults={settings:{startDate:new Date().toISOString().slice(0,10),waterGoal:2500,proteinGoal:160,stepsGoal:8000,bikeGoal:45,rowGoal:20,walkGoal:30,sleepGoal:7},metrics:[],pain:{},daily:{},theme:"light"};
let state=JSON.parse(localStorage.getItem("mfc_state")||"null")||structuredClone(defaults);
state.settings={...defaults.settings,...(state.settings||{})};state.metrics=state.metrics||[];state.pain=state.pain||{};state.daily=state.daily||{};state.theme=state.theme||"light";
const save=()=>localStorage.setItem("mfc_state",JSON.stringify(state));const today=()=>new Date().toISOString().slice(0,10);const pct=(v,g)=>g?Math.min(100,Math.round(v/g*100)):0;
function log(d=today()){state.daily[d]=state.daily[d]||{water:0,protein:[],bike:0,steps:0,row:0,walk:0,sleep:0,done:{}};return state.daily[d]}
const plans={
 strength:[{id:"mob",n:"Mobilität",d:"Cat-Cow 10×, Beckenkippen 15×, Hüftbeuger sanft",m:8},{id:"bridge",n:"Glute Bridge",d:"3×12–15",m:6},{id:"bird",n:"Bird Dog",d:"3×6–8 je Seite",m:6},{id:"row",n:"Kurzhantelrudern",d:"3×10–12",m:7},{id:"press",n:"Schulterdrücken",d:"3×8–10",m:5},{id:"dead",n:"Dead Bug",d:"2×6–10",m:5},{id:"cardio",n:"Ausdauer",d:"10–15 Min locker",m:12},{id:"stretch",n:"Kurz-Stretch",d:"Hüftbeuger und Gesäß je 45 s",m:6}],
 cardio:[{id:"cardio",n:"Ausdauer",d:"45–60 Min E-Bike, Ergometer oder zügiges Gehen",m:50},{id:"stretch",n:"Kurz-Stretch",d:"Hüftbeuger und Gesäß je 45 s",m:6}],
 recovery:[{id:"walk",n:"Lockeres Gehen",d:"20–35 Min ohne Tempozwang",m:30},{id:"mob",n:"Mobilität",d:"Beckenkippen, Cat-Cow, sanfte Hüftbewegung",m:8},{id:"stretch",n:"Kurz-Stretch",d:"Nur sanft",m:5}]
};
function workoutFor(d,p){let day=new Date(d+"T12:00:00").getDay();if(p>=7)return[{id:"acute",n:"Akut-Tag",d:"Nur kurze schmerzarme Spaziergänge und sanfte Bewegung",m:15}];if(p>=4)return plans.recovery;if([1,3,5].includes(day))return plans.strength;if([2,6].includes(day))return plans.cardio;return plans.recovery}
function weekNo(){let s=new Date(state.settings.startDate+"T12:00:00"),n=new Date();return Math.max(1,Math.min(12,Math.floor((n-s)/604800000)+1))}
function render(){document.getElementById("dateLabel").textContent=new Intl.DateTimeFormat("de-DE",{weekday:"long",day:"2-digit",month:"long"}).format(new Date());let p=state.pain[today()]||0;document.getElementById("painRange").value=p;document.getElementById("painValue").textContent=p;document.getElementById("painAdvice").textContent=p>=7?"Heute Belastung stark reduzieren.":p>=4?"Heute reduziertes Programm.":"Normales Programm, solange schmerzarm.";
let l=log(),w=workoutFor(today(),p),html="",done=0,total=0;w.forEach((x,i)=>{let k=x.id+"-"+i,is=!!l.done[k];if(is)done++;total+=x.m;html+=`<div class="workout ${is?"done":""}"><div><h4>${x.n}</h4><p>${x.d}</p></div><button class="taskbtn" data-task="${k}">${is?"✓ Erledigt":"Abschließen"}</button></div>`});document.getElementById("workoutList").innerHTML=html;document.getElementById("durationBadge").textContent=`ca. ${total} Min`;document.getElementById("trainingSummary").textContent=`${done}/${w.length}`;document.getElementById("trainingBar").style.width=pct(done,w.length)+"%";
let ps=l.protein.reduce((a,b)=>a+Number(b),0);document.getElementById("waterGoalLabel").textContent=state.settings.waterGoal+" ml";document.getElementById("waterTotal").textContent=l.water+" ml";document.getElementById("waterBar").style.width=pct(l.water,state.settings.waterGoal)+"%";document.getElementById("proteinGoalLabel").textContent=state.settings.proteinGoal+" g";document.getElementById("proteinTotal").textContent=ps+" g";document.getElementById("proteinBar").style.width=pct(ps,state.settings.proteinGoal)+"%";document.getElementById("proteinEntries").innerHTML=l.protein.map((v,i)=>`<span class="chip">${v} g <button data-del="${i}">×</button></span>`).join("");
["bike","steps","row","walk","sleep"].forEach(k=>document.getElementById(k+"Input").value=l[k]||"");document.getElementById("sleepGoalLabel").textContent=state.settings.sleepGoal+" h";document.getElementById("sleepTotal").textContent=(l.sleep||0)+" h";document.getElementById("sleepBar").style.width=pct(l.sleep,state.settings.sleepGoal)+"%";
let mv=Math.round((pct(l.bike,state.settings.bikeGoal)+pct(l.steps,state.settings.stepsGoal)+pct(l.row,state.settings.rowGoal)+pct(l.walk,state.settings.walkGoal))/4);document.getElementById("movementScore").textContent=mv+" %";document.getElementById("movementBar").style.width=mv+"%";let wn=weekNo();document.getElementById("weekText").textContent="Woche "+wn;document.getElementById("weekRing").style.background=`conic-gradient(var(--accent) ${wn/12*360}deg,#d1d5db 0)`;save()}
function draw(id,key,label){let c=document.getElementById(id),x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);let a=state.metrics.filter(r=>r[key]!=null).slice(-20);x.strokeStyle=getComputedStyle(document.body).getPropertyValue("--line");for(let i=0;i<5;i++){let y=30+i*50;x.beginPath();x.moveTo(45,y);x.lineTo(580,y);x.stroke()}if(!a.length){x.fillStyle="#6b7280";x.fillText("Noch keine Daten",220,145);return}let v=a.map(r=>+r[key]),mi=Math.min(...v)-1,ma=Math.max(...v)+1;x.strokeStyle=getComputedStyle(document.body).getPropertyValue("--accent");x.lineWidth=3;x.beginPath();a.forEach((r,i)=>{let px=50+i*(520/Math.max(1,a.length-1)),py=230-(+r[key]-mi)/(ma-mi)*180;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle=getComputedStyle(document.body).getPropertyValue("--text");x.fillText(`${label}: ${v[v.length-1]}`,45,20)}
function history(){let a=[...state.metrics].sort((a,b)=>b.date.localeCompare(a.date));document.getElementById("history").innerHTML=a.length?`<table><tr><th>Datum</th><th>Gewicht</th><th>Bauch</th></tr>${a.map(r=>`<tr><td>${r.date}</td><td>${r.weight??"–"}</td><td>${r.waist??"–"}</td></tr>`).join("")}</table>`:"Noch keine Einträge.";draw("weightChart","weight","kg");draw("waistChart","waist","cm")}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active");if(b.dataset.tab==="progress")history()});
document.getElementById("painRange").oninput=e=>{state.pain[today()]=+e.target.value;render()};
document.getElementById("workoutList").onclick=e=>{if(!e.target.dataset.task)return;let l=log();l.done[e.target.dataset.task]=!l.done[e.target.dataset.task];render()};
document.querySelectorAll("[data-water]").forEach(b=>b.onclick=()=>{let l=log();l.water=Math.max(0,l.water+Number(b.dataset.water));render()});
document.getElementById("addProtein").onclick=()=>{let v=+document.getElementById("proteinInput").value;if(v>0){log().protein.push(v);document.getElementById("proteinInput").value="";render()}};
document.getElementById("proteinEntries").onclick=e=>{if(e.target.dataset.del===undefined)return;log().protein.splice(+e.target.dataset.del,1);render()};
document.getElementById("saveMovement").onclick=()=>{let l=log();["bike","steps","row","walk"].forEach(k=>l[k]=Math.max(0,+document.getElementById(k+"Input").value||0));render()};
document.getElementById("saveSleep").onclick=()=>{log().sleep=Math.max(0,+document.getElementById("sleepInput").value||0);render()};
document.getElementById("saveMetrics").onclick=()=>{let w=+document.getElementById("weightInput").value,wa=+document.getElementById("waistInput").value,r=state.metrics.find(x=>x.date===today());if(!r){r={date:today()};state.metrics.push(r)}if(w)r.weight=w;if(wa)r.waist=wa;save();alert("Gespeichert")};
function loadSettings(){["waterGoal","proteinGoal","stepsGoal","bikeGoal","rowGoal","walkGoal","sleepGoal","startDate"].forEach(k=>document.getElementById(k).value=state.settings[k])}
document.getElementById("saveSettings").onclick=()=>{["waterGoal","proteinGoal","stepsGoal","bikeGoal","rowGoal","walkGoal","sleepGoal"].forEach(k=>state.settings[k]=+document.getElementById(k).value);state.settings.startDate=document.getElementById("startDate").value;save();render();alert("Einstellungen gespeichert")};
document.getElementById("themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";document.body.classList.toggle("dark",state.theme==="dark");save()};
document.getElementById("exportBtn").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="michael-fitness-daten.json";a.click()};
document.getElementById("importInput").onchange=e=>{let f=e.target.files[0],r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);save();location.reload()};r.readAsText(f)};
document.getElementById("resetBtn").onclick=()=>{if(confirm("Wirklich löschen?")){localStorage.removeItem("mfc_state");location.reload()}};
document.body.classList.toggle("dark",state.theme==="dark");loadSettings();render();history();
let ws=document.getElementById("weekSelector");for(let i=1;i<=12;i++)ws.innerHTML+=`<button class="weekbtn" data-w="${i}">W${i}</button>`;ws.onclick=e=>{if(!e.target.dataset.w)return;document.querySelectorAll(".weekbtn").forEach(b=>b.classList.toggle("active",b===e.target));let s=new Date(state.settings.startDate+"T12:00:00");s.setDate(s.getDate()+(+e.target.dataset.w-1)*7);let h="";for(let i=0;i<7;i++){let d=new Date(s);d.setDate(s.getDate()+i),ds=d.toISOString().slice(0,10);h+=`<div class="dayrow"><strong>${["So","Mo","Di","Mi","Do","Fr","Sa"][d.getDay()]}</strong><span>${workoutFor(ds,state.pain[ds]||0).map(x=>x.n).join(", ")}</span></div>`}document.getElementById("weekPlan").innerHTML=h};ws.querySelector(`[data-w="${weekNo()}"]`).click();
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
